server:
  port: 0

stats-server:
  url: http://stats-server
spring:
  application:
    name: main-service
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7654/ewm-main
    username: user
    password: password

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/